name: data_saver
description: Simple Flutter plugin to check the current Data Saver/Low Data Mode.
version: 0.3.0
repository: https://github.com/n-bernat/data_saver
issue_tracker: https://github.com/n-bernat/data_saver/issues

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^13.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.nikodembernat.data_saver
        pluginClass: DataSaverPlugin
      ios:
        pluginClass: DataSaverPlugin
      macos:
        pluginClass: DataSaverPlugin
      web:
        pluginClass: DataSaverWeb
        fileName: src/web/data_saver_web.dart
