# flutter_tests_*.yaml actions are duplicated, because GitHub doesn't support badges for matrix builds.
name: data_saver - Tests (beta)
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    timeout-minutes: 5
    name: Flutter tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "beta"

      - name: Print version
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format . --set-exit-if-changed

      - name: Run analyzer
        run: flutter analyze

      - name: Run tests
        run: flutter test .
