name: Tag packages
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Tag packages
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: Test packages
        uses: n-bernat/flutter-tools/packages/test@master

      - name: Tag packages
        uses: n-bernat/flutter-tools/packages/tag@master
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
